export const SERVERCOMMANDS = {
    CONNECT: 'connect',
    PROMPT: 'prompt',
    NEW_PROJECT: 'newProject',
    OPEN_PROJECT: 'openProject',
    SAVE_PROJECT: 'saveProject',
    CLOSE_PROJECT: 'closeProject',
    LOAD_FILE: 'loadFile',
    SAVE_FILE: 'saveFile',
    DELETE_FILE: 'deleteFile',
    RENAME_FILE: 'renameFile',
    COPY_FILE: 'copyFile',
    MOVE_FILE: 'moveFile',
    CREATE_FOLDER: 'createFolder',
    DELETE_FOLDER: 'deleteFolder',
    RENAME_FOLDER: 'renameFolder',
    COPY_FOLDER: 'copyFolder',
    MOVE_FOLDER: 'moveFolder',
    CREATE_ACCOUNT: 'createAccount',
    LOGIN: 'login',
    GET_TEMPLATES: 'getTemplates',
    RELOAD_FILE: 'reloadFile',
    GET_PROJECT_LIST: 'getProjectList'
};